
# This is a basic workflow to compile the program and run unit tests
# This is aimed at C or C++ projects, but can be adapted for other languages

name: 'Compile and Test'
on:
  push:
    branches:
      - migration
  pull_request:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile with make
        run: make
      - name: Clean with make
        run: make fclean
